const APP_VERSION='5.4.2-pages';
const REPO='https://github.com/ducngt/LIS1';
const ISSUE_URL=REPO+'/issues/new?template=blank_issues_enabled=true&title=%5BFeedback%5D%20NUTE%20RIS%20Demo';
const roles={
  SYSTEM_ADMIN:{label:'Admin',permissions:['*']},
  RESEARCH_PARTICIPANT:{label:'Cá nhân tham gia',permissions:['research.create','research.submit','research.read.self','profile.manage','ai.use']},
  APPROVER_LEVEL_2:{label:'Bộ môn/Khoa/Hội đồng',permissions:['research.read.unit','research.approve.level2','ai.use']},
  APPROVER_LEVEL_3:{label:'Phòng/Trung tâm',permissions:['research.read.all','research.approve.level3','ai.use']},
  APPROVER_LEVEL_4:{label:'Hiệu trưởng/BGH',permissions:['research.read.all','research.approve.level4','ai.use']}
};
const accounts=[
  {username:'admin',password:'admin123',displayName:'Quản trị RIS',role:'SYSTEM_ADMIN',org:'Toàn trường'},
  {username:'researcher',password:'demo123',displayName:'Nguyễn Văn Nghiên cứu',role:'RESEARCH_PARTICIPANT',org:'Khoa Công nghệ Thông tin'},
  {username:'level2',password:'demo123',displayName:'Trưởng Khoa',role:'APPROVER_LEVEL_2',org:'Khoa Công nghệ Thông tin'},
  {username:'level3',password:'demo123',displayName:'Phòng Khoa học Công nghệ',role:'APPROVER_LEVEL_3',org:'Phòng KHCN'},
  {username:'level4',password:'demo123',displayName:'Ban Giám hiệu',role:'APPROVER_LEVEL_4',org:'Ban Giám hiệu'}
];
const workflow=['DRAFT','SUBMITTED','LEVEL2_APPROVED','LEVEL3_APPROVED','APPROVED','IN_PROGRESS','RESULT_SUBMITTED','COUNCIL_REVIEW','COMPLETED','RECOGNIZED'];
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const load=()=>JSON.parse(localStorage.getItem('nute_ris_demo_state')||'null')||seed();
const save=()=>localStorage.setItem('nute_ris_demo_state',JSON.stringify(state.db));
function seed(){return {organizations:['Khoa Công nghệ Thông tin','Khoa Cơ khí','Phòng KHCN','Ban Giám hiệu'],research:[{id:'R001',title:'Ứng dụng AI trong hỗ trợ học tập',owner:'researcher',ownerName:'Nguyễn Văn Nghiên cứu',organization:'Khoa Công nghệ Thông tin',type:'Đề tài cấp Trường',status:'SUBMITTED',createdAt:new Date().toISOString(),history:[{at:new Date().toISOString(),status:'DRAFT',by:'researcher'},{at:new Date().toISOString(),status:'SUBMITTED',by:'researcher'}]}],profiles:{researcher:{orcid:'',scopusId:'',expertise:'AI, giáo dục kỹ thuật',keywords:'LLM, RAG, AI-Native'}},feedback:[]}}
const state={user:null,route:'dashboard',db:load()};
function has(p){return state.user&& (roles[state.user.role].permissions.includes('*')||roles[state.user.role].permissions.includes(p))}
function renderLogin(msg=''){document.body.innerHTML=`<div id="app"><div class="center"><form class="auth" id="login"><div class="brand-login"><img src="./logo-nute.jpg"><div><h1>NUTE AI-Native RIS</h1><p>GitHub Pages Demo · ${APP_VERSION}</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<div class="field"><label>Tài khoản</label><input name="username" required autofocus></div><div class="field"><label>Mật khẩu</label><input name="password" type="password" required></div><button class="btn primary" style="width:100%">Đăng nhập</button><div class="notice"><b>Bản dùng thử trên GitHub Pages.</b> Dữ liệu chỉ lưu trong trình duyệt của từng người dùng. Không có secret/API key dùng chung.</div><div class="demo-accounts">${accounts.map(a=>`<div class="demo-account" data-demo="${a.username}"><b>${a.displayName}</b><small>${a.username} / ${a.password}</small></div>`).join('')}</div></form></div></div>`;$('#login').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const u=accounts.find(a=>a.username===f.username&&a.password===f.password);if(!u)return alert('Sai tài khoản hoặc mật khẩu demo.');state.user=u;renderShell();go('dashboard')};document.querySelectorAll('[data-demo]').forEach(x=>x.onclick=()=>{const a=accounts.find(a=>a.username===x.dataset.demo);$('#login [name=username]').value=a.username;$('#login [name=password]').value=a.password})}
function renderShell(){document.body.innerHTML=`<div id="app"><div class="shell"><aside class="sidebar"><div class="brand"><img src="./logo-nute.jpg"><div><strong>NUTE Research</strong><small>GitHub Pages Demo · ${APP_VERSION}</small></div></div><nav class="nav"><button data-route="dashboard">Tổng quan</button><div class="section">Nghiên cứu</div><button data-route="research">Hồ sơ nghiên cứu</button><button data-route="copilot">AI Research Copilot</button><button data-route="profile">Hồ sơ năng lực</button>${has('*')?'<div class="section">Quản trị</div><button data-route="organizations">Đơn vị</button><button data-route="accounts">Tài khoản demo</button>':''}</nav></aside><main class="main"><header class="topbar"><span class="ai-chip"><i></i> AI-NATIVE WORKSPACE</span><div class="who"><div class="avatar">${esc(state.user.displayName[0])}</div><div><b>${esc(state.user.displayName)}</b><small>${esc(roles[state.user.role].label)} · ${esc(state.user.org)}</small></div><button class="btn sm" id="logout">Đăng xuất</button></div></header><section class="content" id="view"></section></main></div><div class="feedback"><a class="btn primary" target="_blank" rel="noopener" href="${ISSUE_URL}">Góp ý trên GitHub</a></div></div>`;document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));$('#logout').onclick=()=>renderLogin('Đã đăng xuất.');}
function go(r){state.route=r;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===r));if(r==='dashboard')dashboard();if(r==='research')research();if(r==='copilot')copilot();if(r==='profile')profile();if(r==='organizations')organizations();if(r==='accounts')accountList()}
function visibleResearch(){if(has('research.read.all')||has('*'))return state.db.research;if(has('research.read.unit'))return state.db.research.filter(r=>r.organization===state.user.org);return state.db.research.filter(r=>r.owner===state.user.username)}
function dashboard(){const rows=visibleResearch();const active=rows.filter(r=>!['RECOGNIZED'].includes(r.status)).length;const need=rows.filter(r=>['SUBMITTED','LEVEL2_APPROVED','LEVEL3_APPROVED','REVISION_REQUIRED'].includes(r.status)).length;$('#view').innerHTML=`<div class="page-head"><div><h2>Tổng quan nghiên cứu</h2><p>Demo tương tác trực tiếp từ GitHub Pages. Workflow và dữ liệu được lưu trong trình duyệt của bạn.</p></div></div><div class="grid cards"><div class="card metric"><div class="label">Tổng hồ sơ</div><div class="num">${rows.length}</div></div><div class="card metric"><div class="label">Đang chạy</div><div class="num">${active}</div></div><div class="card metric"><div class="label">Cần xử lý</div><div class="num">${need}</div></div><div class="card metric"><div class="label">Đã công nhận</div><div class="num">${rows.filter(r=>r.status==='RECOGNIZED').length}</div></div></div><div class="card" style="margin-top:18px"><h3>Luồng hồ sơ đang chạy</h3>${rows.length?rows.map(r=>`<div style="padding:14px 0;border-bottom:1px solid #edf1f7"><b>${esc(r.title)}</b><div class="muted">${esc(r.organization)} · <span class="status ${r.status}">${r.status}</span></div><div class="flow" style="margin-top:10px">${workflow.slice(0,5).map(s=>`<span class="step ${s===r.status?'current':''}">${s}</span>`).join('')}</div></div>`).join(''):'<div class="muted">Chưa có hồ sơ.</div>'}</div>`}
function research(){const rows=visibleResearch();$('#view').innerHTML=`<div class="page-head"><div><h2>Hồ sơ nghiên cứu</h2><p>Đăng ký, phê duyệt nhiều cấp và trả lại chỉnh sửa theo Human + AI workflow.</p></div>${has('research.create')||has('*')?'<button class="btn primary" id="newResearch">+ Đăng ký hồ sơ</button>':''}</div><div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Hồ sơ</th><th>Đơn vị</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.id}</td><td><b>${esc(r.title)}</b><br><span class="muted">${esc(r.type)}</span></td><td>${esc(r.organization)}</td><td><span class="status ${r.status}">${r.status}</span></td><td>${actionsFor(r).map(a=>`<button class="btn sm" data-act="${a.action}" data-id="${r.id}">${a.label}</button>`).join(' ')||'<span class="muted">—</span>'}</td></tr>`).join('')}</tbody></table></div>`;$('#newResearch')?.addEventListener('click',newResearch);document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>applyAction(b.dataset.id,b.dataset.act))}
function actionsFor(r){const a=[];if((has('research.submit')||has('*'))&&r.owner===state.user.username){if(r.status==='DRAFT'||r.status==='REVISION_REQUIRED')a.push({action:'SUBMIT',label:r.status==='DRAFT'?'Gửi đăng ký':'Gửi lại'});if(r.status==='APPROVED')a.push({action:'START',label:'Bắt đầu thực hiện'})}if((has('research.approve.level2')||has('*'))&&r.status==='SUBMITTED'){a.push({action:'L2_OK',label:'Duyệt cấp 2'},{action:'RETURN',label:'Trả lại'})}if((has('research.approve.level3')||has('*'))&&r.status==='LEVEL2_APPROVED'){a.push({action:'L3_OK',label:'Duyệt cấp 3'},{action:'RETURN',label:'Trả lại'})}if((has('research.approve.level4')||has('*'))&&r.status==='LEVEL3_APPROVED'){a.push({action:'L4_OK',label:'Duyệt cấp 4'},{action:'RETURN',label:'Trả lại'})}return a}
function newResearch(){modal(`<h3>Đăng ký hồ sơ nghiên cứu</h3><form id="rf"><div class="field"><label>Tên hồ sơ</label><input name="title" required></div><div class="field"><label>Loại hoạt động</label><select name="type"><option>Đề tài cấp Trường</option><option>Công trình công bố</option><option>Sáng kiến</option><option>Sở hữu trí tuệ</option></select></div><div class="field"><label>Đơn vị</label><select name="organization">${state.db.organizations.map(o=>`<option ${o===state.user.org?'selected':''}>${esc(o)}</option>`).join('')}</select></div><div class="actions"><button type="button" class="btn" data-close>Hủy</button><button class="btn primary">Tạo hồ sơ</button></div></form>`);$('#rf').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.db.research.push({id:'R'+String(Date.now()).slice(-6),title:f.title,type:f.type,organization:f.organization,owner:state.user.username,ownerName:state.user.displayName,status:'DRAFT',createdAt:new Date().toISOString(),history:[]});save();closeModal();research()}}
function applyAction(id,action){const r=state.db.research.find(x=>x.id===id);if(!r)return;const map={SUBMIT:'SUBMITTED',L2_OK:'LEVEL2_APPROVED',L3_OK:'LEVEL3_APPROVED',L4_OK:'APPROVED',RETURN:'REVISION_REQUIRED',START:'IN_PROGRESS'};const next=map[action];if(!next)return;const humanDecision=['L2_OK','L3_OK','L4_OK','RETURN'].includes(action);const reason=humanDecision?prompt('Nhập lý do/căn cứ quyết định (Human quyết định):','Đã xem xét hồ sơ và khuyến nghị AI demo.'):'';if(humanDecision&&reason===null)return;r.status=next;r.history.push({at:new Date().toISOString(),status:next,by:state.user.username,reason:reason||''});save();research()}
function copilot(){$('#view').innerHTML=`<div class="page-head"><div><h2>AI Research Copilot</h2><p>Trong GitHub Pages Demo, AI được mô phỏng để đánh giá UX mà không công khai API key.</p></div></div><div class="ai-box"><div class="field"><label>Nhiệm vụ</label><select id="task"><option>Kiểm tra tính đầy đủ hồ sơ</option><option>Phản biện phương pháp nghiên cứu</option><option>Đề xuất bước tiếp theo</option></select></div><div class="field"><label>Nội dung cần phân tích</label><textarea id="aiInput" rows="9" placeholder="Nhập nội dung nghiên cứu..."></textarea></div><button class="btn primary" id="analyze">Phân tích bằng AI Demo</button><div id="aiResult"></div></div>`;$('#analyze').onclick=()=>{const t=$('#aiInput').value.trim();if(!t)return alert('Hãy nhập nội dung.');$('#aiResult').innerHTML=`<pre><b>AI Decision Support (Demo)</b>\n\nDữ kiện: Nội dung đã được tiếp nhận.\nThiếu hụt: Cần kiểm tra minh chứng và quy định áp dụng.\nRủi ro: Chưa có đủ ngữ cảnh để kết luận thay con người.\nKhuyến nghị: Đối chiếu mục tiêu - phương pháp - sản phẩm; bổ sung căn cứ và minh chứng trước khi gửi duyệt.\n\nHuman authority: Quyết định cuối cùng thuộc người có thẩm quyền.</pre>`}}
function profile(){const p=state.db.profiles[state.user.username]||{};$('#view').innerHTML=`<div class="page-head"><div><h2>Hồ sơ năng lực nghiên cứu</h2><p>Đơn vị được liên kết với tài khoản demo và cấu trúc tổ chức.</p></div></div><div class="card"><div class="grid" style="grid-template-columns:1fr 1fr"><div class="field"><label>Họ tên</label><input value="${esc(state.user.displayName)}" readonly></div><div class="field"><label>Đơn vị</label><input value="${esc(state.user.org)}" readonly></div></div><form id="pf"><div class="grid" style="grid-template-columns:1fr 1fr"><div class="field"><label>ORCID</label><input name="orcid" value="${esc(p.orcid||'')}"></div><div class="field"><label>Scopus ID</label><input name="scopusId" value="${esc(p.scopusId||'')}"></div></div><div class="field"><label>Lĩnh vực chuyên môn</label><input name="expertise" value="${esc(p.expertise||'')}"></div><div class="field"><label>Từ khóa</label><input name="keywords" value="${esc(p.keywords||'')}"></div><button class="btn primary">Lưu hồ sơ</button></form></div>`;$('#pf').onsubmit=e=>{e.preventDefault();state.db.profiles[state.user.username]=Object.fromEntries(new FormData(e.target));save();alert('Đã lưu trên trình duyệt này.')}}
function organizations(){$('#view').innerHTML=`<div class="page-head"><div><h2>Đơn vị</h2><p>Danh mục tổ chức dùng trong bản demo.</p></div></div><div class="card">${state.db.organizations.map(o=>`<div style="padding:10px 0;border-bottom:1px solid #edf1f7">${esc(o)}</div>`).join('')}</div>`}
function accountList(){$('#view').innerHTML=`<div class="page-head"><div><h2>Tài khoản demo</h2><p>Các tài khoản dùng thử công khai trên GitHub Pages.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Tài khoản</th><th>Người dùng</th><th>Vai trò</th><th>Đơn vị</th></tr></thead><tbody>${accounts.map(a=>`<tr><td>${a.username}</td><td>${esc(a.displayName)}</td><td>${esc(roles[a.role].label)}</td><td>${esc(a.org)}</td></tr>`).join('')}</tbody></table></div>`}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal">${html}</div></div>`);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}function closeModal(){$('#modal')?.remove()}
renderLogin();
